-- ==========================================
-- SUPABASE POSTGRESQL SCHEMA
-- Cópialo y pégalo en el "SQL Editor" de Supabase
-- ==========================================

-- 1. Usuarios
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT,
    username TEXT UNIQUE,
    password TEXT,
    rol TEXT CHECK (rol IN ('super_admin', 'admin', 'docente')),
    estado_password TEXT DEFAULT 'temporal',
    avatar_url TEXT DEFAULT '',
    telefono TEXT DEFAULT '',
    is_private BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Progreso de Módulos
CREATE TABLE IF NOT EXISTS public.progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    module_1_progress INTEGER DEFAULT 0,
    module_2_progress INTEGER DEFAULT 0,
    module_3_progress INTEGER DEFAULT 0,
    module_4_progress INTEGER DEFAULT 0,
    total_progress INTEGER DEFAULT 0,
    is_certified BOOLEAN DEFAULT false
);

-- 3. Recursos de Módulos (Materiales de Clase)
CREATE TABLE IF NOT EXISTS public.module_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id INTEGER,
    week_id INTEGER,
    title TEXT,
    type TEXT,
    url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Configuración de Exámenes (Fechas de apertura/cierre)
CREATE TABLE IF NOT EXISTS public.exams_config (
    module_id INTEGER PRIMARY KEY,
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE
);

-- 5. Intentos de Exámenes
CREATE TABLE IF NOT EXISTS public.exam_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    module_id INTEGER,
    attempts INTEGER DEFAULT 0,
    grade REAL DEFAULT 0,
    is_passed BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'en_progreso', -- 'en_progreso', 'pendiente_revision', 'calificado'
    ai_flag BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Preguntas (Constructor de Evaluaciones)
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id INTEGER,
    type TEXT, -- 'multiple', 'tf', 'link'
    text TEXT,
    options_json TEXT, -- JSON array
    correct_answer TEXT,
    image_url TEXT,
    points REAL DEFAULT 1
);

-- 7. Respuestas del Estudiante
CREATE TABLE IF NOT EXISTS public.user_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT REFERENCES public.exam_attempts(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    student_answer TEXT,
    file_url TEXT,
    points_awarded REAL DEFAULT 0
);

-- 8. Registro de Auditoría (Audit Logs)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT,
    admin_name TEXT,
    action TEXT,
    details_json TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- INSERTAR DATOS INICIALES POR DEFECTO
-- ==========================================

-- Insertar Super Admin Inicial
INSERT INTO public.users (nombre, username, password, rol, estado_password) 
VALUES ('Super Admin', 'admin', 'admin', 'super_admin', 'permanente') 
ON CONFLICT (username) DO NOTHING;

-- Configuración de Módulos (Bloqueados por defecto)
INSERT INTO public.exams_config (module_id, start_time, end_time) VALUES 
(1, '2000-01-01T00:00:00.000Z', '2000-01-01T00:00:00.000Z'),
(2, '2000-01-01T00:00:00.000Z', '2000-01-01T00:00:00.000Z'),
(3, '2000-01-01T00:00:00.000Z', '2000-01-01T00:00:00.000Z'),
(4, '2000-01-01T00:00:00.000Z', '2000-01-01T00:00:00.000Z')
ON CONFLICT (module_id) DO NOTHING;

-- ==========================================
-- DESHABILITAR RLS (Row Level Security)
-- Al ser un proyecto "Serverless" donde el front-end hace las consultas
-- directamente, necesitamos que las tablas sean públicas.
-- ==========================================
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.module_resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.exams_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_attempts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_answers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- HABILITAR REALTIME (WebSockets)
-- Permite que los cambios caigan "silenciosamente" y en vivo.
-- ==========================================
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR TABLE 
    public.users,
    public.progress,
    public.exams_config,
    public.exam_attempts;
COMMIT;

-- ==========================================
-- CREACIÓN DE STORAGE BUCKET (Para Fotos y Archivos)
-- ==========================================
INSERT INTO storage.buckets (id, name, public) 
VALUES ('archivos', 'archivos', true)
ON CONFLICT (id) DO NOTHING;

-- Dar permisos públicos para que cualquiera pueda subir/ver archivos (Modo Serverless frontend)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR ALL USING (bucket_id = 'archivos');
